name: TrackHobbies
options:
  bundleIdPrefix: com.trackhobbies
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  TrackHobbies:
    type: application
    platform: iOS
    sources:
      - path: AppMain.swift
      - path: BookStore.swift
      - path: ContentView.swift
      - path: Models
      - path: Models.swift
      - path: NotionExporter.swift
      - path: Services
      - path: Sync
      - path: Utils
      - path: Theme
      - path: Views
      - path: ViewModels
      - path: Assets.xcassets
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.trackhobbies.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: TrackHobbies.entitlements
    entitlements:
      path: TrackHobbies.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.trackhobbies.app
        com.apple.developer.icloud-services:
          - CloudKit
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: TrackHobbies
        CFBundleName: TrackHobbies
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true

  TrackHobbiesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: TrackHobbies
    settings:
      base:
        INFOPLIST_FILE: Tests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.trackhobbies.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TrackHobbies.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TrackHobbies"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  TrackHobbies:
    build:
      targets:
        TrackHobbies: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TrackHobbiesTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
